---
title: "Underreporting Simulations"
author: "Andrea Brizzi"
date: "08/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Dependencies
require(EpiEstim)
require(dplyr)
require(ggplot2)
require(png)
require(ggpubr)

# set up directories' paths
repo_path <-  '~/Documents/mini_project_2/R0_simulations'
# setwd(repo_path)
data_path <- file.path('~/Documents/mini_project_2/R0_simulations/data')
plots_path <- '~/Documents/mini_project_2/plots'

# sources 
source(file.path(repo_path,"scripts/methods.R"))

# extracts legend
g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}
```

Under-reporting is modeled as: 
$$
y_t \sim \text{Binom}(I_t, \rho).
$$

```{r}
sims_SEIR <- readRDS(file.path(data_path, "sims_SEIR"))
names <- names(sims_SEIR)[c(2,4,6,8)]

# generation interval parameters
mean_si <- 6.5
sd_si <- sqrt(3^2 + 3.5^2)

# dataframe for coverage and CI width:
coverage_stats <- data.frame(method = as.character(),
                             coverage = as.numeric(),
                             R0 = as.character(),
                             CIwidth = as.numeric(),
                             rho = as.numeric(),
                             q_Rt05 = as.numeric(),
                             q_Rt50 = as.numeric(),
                             q_Rt95 = as.numeric()
                             )

if.plots <- FALSE
```

## Results {.tabset}

### rho = 1

Let's code!
```{r, warning=FALSE, message = FALSE}

# reporting rate
rho <- 1

# Problems showing plots: maybe store them in a list
list_plots <- list()
final_stats <- data.frame(method = as.character(),
                          coverage = as.numeric(),
                          R0 = as.character(),
                          CIwidth = as.numeric(),
                          q_Rt05 = as.numeric(),
                          q_Rt50 = as.numeric(),
                          q_Rt95 = as.numeric()
                          )

estimated_starts <- data.frame(R0 = as.character(),
                               estimate = as.numeric())

for (name in names){
  
  # Transform the data
  df <- as.data.frame(sims_SEIR[[name]])
  df$day <- 1:(dim(df)[1])
  
  # Now cut off 2 weeks of data
  df <- filter(df, day > 2*7)
  
  results <- data.frame(sim = as.numeric(),
                        method = as.character(),
                        R0 = as.numeric(),
                        lowR0 = as.numeric(),
                        upR0 = as.numeric())
  
  
  # For every possible simulation
  for(c in 1:(ncol(df - 1))){
    
    # Get incidence
    incidence <- data.frame(cases = df[,c])
    incidence$cases <- rbinom(n = length(incidence$cases),
                              size = incidence$cases,
                              prob = rho)
    incidence$day <- 2*7 + 1:dim(incidence)[1]
    
    # Make sure there are cases in the first 2 observed weeks...
    somecases <- (sum(incidence$cases[1:14]) >= 12)
    
    if (somecases){
      #== simple EpiEstim: biweekly sliding window
      
      epestim <- epiestim(incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si)
    
      results <- rbind(results, data.frame(
        sim = c, method = 'simpleEpiEstim', R0 = epestim[1],
        lowR0 = epestim[2], upR0 = epestim[3]
      ))
      
      
      #== Linear Exponential Growth: estimate using first 2 weeks 
      if(any(incidence$cases==0)){
        incidence$casesC <- incidence$cases+0.5
        incidence$logcases <- log(incidence$casesC)
      }else{
        incidence$logcases <- log(incidence$cases)
      }
      
      eglin <- EG_Lin(data = incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si)
      
      results <- rbind(results, data.frame(
        sim = c, method = 'EgLin', R0 = eglin[1],
        lowR0 = eglin[2], upR0 = eglin[3]
      ))
      
      
     
      #== EpiEstim with correction

      epestim2 <- epiestim_adjust(data = incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si, adjust = TRUE)
      
      epestim2 <- epestim2$results
      results <- rbind(results, data.frame(
          sim = c, method = 'EpiEstim_adjusted', R0 = epestim2[1],
          lowR0 = epestim2[2], upR0 = epestim2[3]
      ))
      
    }
  }
    
    
  rownames(results) <- c()
  
  
  # show results:
  trueR0 <- as.numeric(stringr::str_match(name, "R0=\\s*(.*?)\\s*pop")[2])
  
  results$method <- as.factor(plyr::revalue(results$method, 
                                            c("EgLin"="EG", "EpiEstim_adjusted"="EpEsAdj", "simpleEpiEstim"="EpEs")))
  results <- results %>% group_by(method)
  
  # This is stupid but otherwise I can t get it to work:
  if(trueR0 == 1.5){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 1.5),col = "red", linetype = "dashed")
  }
  if(trueR0 == 2){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 2),col = "red", linetype = "dashed")
  }
  if(trueR0 == 2.5){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 2.5),col = "red", linetype = "dashed")
  }
  if(trueR0 == 3){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 3),col = "red", linetype = "dashed")
  }
  
  # fix style
  gg <- gg + theme_minimal() +  theme(legend.position = 'none') + labs( x = '', y = 'R0 estimate')
  # common xylimits
  gg <- gg + ylim(c(0,4))
  
  list_plots[[name]] <- gg
  # ggsave(file.path(plots_path, paste0("underreporting_1",name, ".png")), gg, w=10, h=8)
  
  results$inside <- (trueR0 <= results$upR0 & trueR0 >= results$lowR0)
  results$CIwidth <- results$upR0 - results$lowR0

  tmp <- results %>% group_by(method) %>%
    summarise(coverage = mean(inside), CIwidth = mean(CIwidth),
              q_Rt05 = quantile(R0, .05), q_Rt50 = quantile(R0, .50), q_Rt95 = quantile(R0, .95),
              R0 = trueR0)
  
  final_stats <- rbind(final_stats, tmp)
  
}
knitr::kable(final_stats)

final_stats$rho <- rho
coverage_stats <- rbind(coverage_stats, final_stats)

figure <- ggarrange(list_plots[[names[1]]], list_plots[[names[2]]], list_plots[[names[3]]], list_plots[[names[4]]],
                    labels = c("R0 = 1.5", "R0 = 2", "R0 = 2.5", "R0 = 3"),
                    ncol = 2, nrow = 2)
figure
ggsave(file.path(plots_path,paste0('figure2_sens',rho,'.png')),figure, w = 10, h = 6.5)
ggsave(file.path(plots_path,paste0('figure2_sens',rho,'.pdf')),figure, w = 10, h = 6.5)

```

### rho = 0.5

Let's a code!
```{r, warning=FALSE, message = FALSE}

# reporting rate
rho <- .5

# Problems showing plots: maybe store them in a list
list_plots <- list()
final_stats <- data.frame(method = as.character(),
                          coverage = as.numeric(),
                          R0 = as.character(),
                          CIwidth = as.numeric())

estimated_starts <- data.frame(R0 = as.character(),
                               estimate = as.numeric())

for (name in names){
  
  # Transform the data
  df <- as.data.frame(sims_SEIR[[name]])
  df$day <- 1:(dim(df)[1])
  
  # Now cut off 2 weeks of data
  df <- filter(df, day > 2*7)
  
  results <- data.frame(sim = as.numeric(),
                        method = as.character(),
                        R0 = as.numeric(),
                        lowR0 = as.numeric(),
                        upR0 = as.numeric())
  
  
  # For every possible simulation
  for(c in 1:(ncol(df - 1))){
    
    # Get incidence
    incidence <- data.frame(cases = df[,c])
    incidence$cases <- rbinom(n = length(incidence$cases),
                              size = incidence$cases,
                              prob = rho)
    incidence$day <- 2*7 + 1:dim(incidence)[1]
    
    # Make sure there are cases in the first 2 observed weeks...
    somecases <- (sum(incidence$cases[1:14]) >= 12)
    
    if (somecases){
      #== simple EpiEstim: biweekly sliding window
      
      epestim <- epiestim(incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si)
    
      results <- rbind(results, data.frame(
        sim = c, method = 'simpleEpiEstim', R0 = epestim[1],
        lowR0 = epestim[2], upR0 = epestim[3]
      ))
      
      
      #== Linear Exponential Growth: estimate using first 2 weeks 
      if(any(incidence$cases==0)){
        incidence$casesC <- incidence$cases+0.5
        incidence$logcases <- log(incidence$casesC)
      }else{
        incidence$logcases <- log(incidence$cases)
      }
      
      eglin <- EG_Lin(data = incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si)
      
      results <- rbind(results, data.frame(
        sim = c, method = 'EgLin', R0 = eglin[1],
        lowR0 = eglin[2], upR0 = eglin[3]
      ))
      
      
     
      #== EpiEstim with correction
      
      ## Mine as well
      epestim2 <- epiestim_adjust(data = incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si, adjust = TRUE)
      
      epestim2 <- epestim2$results
      results <- rbind(results, data.frame(
          sim = c, method = 'EpiEstim_adjusted', R0 = epestim2[1],
          lowR0 = epestim2[2], upR0 = epestim2[3]
      ))
      
    }
  }
    
    
  rownames(results) <- c()
  
  
  # show results:
  trueR0 <- as.numeric(stringr::str_match(name, "R0=\\s*(.*?)\\s*pop")[2])
  
  results$method <- as.factor(plyr::revalue(results$method, 
                                            c("EgLin"="EG", "EpiEstim_adjusted"="EpEsAdj", "simpleEpiEstim"="EpEs")))
  results <- results %>% group_by(method)
  
  
  
  
  # This is stupid but otherwise I can t get it to work:
  if(trueR0 == 1.5){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 1.5),col = "red", linetype = "dashed")
  }
  if(trueR0 == 2){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 2),col = "red", linetype = "dashed")
  }
  if(trueR0 == 2.5){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 2.5),col = "red", linetype = "dashed")
  }
  if(trueR0 == 3){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 3),col = "red", linetype = "dashed")
  }
  
  # fix style
  gg <- gg + theme_minimal() +  theme(legend.position = 'none') + labs( x = '', y = 'R0 median estimate')
  # common xylimits
  gg <- gg + ylim(c(0,4))
  
  list_plots[[name]] <- gg
  # ggsave(plot = gg, filename = file.path(plots_path, paste0("underreporting_.5",name, ".png")))
  
  results$inside <- (trueR0 <= results$upR0 & trueR0 >= results$lowR0)
  results$CIwidth <- results$upR0 - results$lowR0

  tmp <- results %>% group_by(method) %>%
      summarise(coverage = mean(inside), CIwidth = mean(CIwidth),
              q_Rt05 = quantile(R0, .05), q_Rt50 = quantile(R0, .50), q_Rt95 = quantile(R0, .95),
              R0 = trueR0)
  
  final_stats <- rbind(final_stats, tmp)
  
  
}

knitr::kable(final_stats)

final_stats$rho <- rho
coverage_stats <- rbind(coverage_stats, final_stats)

figure <- ggarrange(list_plots[[names[1]]], list_plots[[names[2]]], list_plots[[names[3]]], list_plots[[names[4]]],
                    labels = c("R0 = 1.5", "R0 = 2", "R0 = 2.5", "R0 = 3"),
                    ncol = 2, nrow = 2)
figure
ggsave(file.path(plots_path,'figure2.png'),figure, w = 10, h = 6.5)
ggsave(file.path(plots_path,'figure2.pdf'),figure, w = 10, h = 6.5)
```

### rho = 0.3

Let's a code!
```{r, warning=FALSE, message = FALSE}

# reporting rate
rho <- .3

# Problems showing plots: maybe store them in a list
list_plots <- list()
final_stats <- data.frame(method = as.character(),
                          coverage = as.numeric(),
                          R0 = as.character(),
                          CIwidth = as.numeric())

estimated_starts <- data.frame(R0 = as.character(),
                               estimate = as.numeric())

for (name in names){
  
  # Transform the data
  df <- as.data.frame(sims_SEIR[[name]])
  df$day <- 1:(dim(df)[1])
  
  # Now cut off 2 weeks of data
  df <- filter(df, day > 2*7)
  
  results <- data.frame(sim = as.numeric(),
                        method = as.character(),
                        R0 = as.numeric(),
                        lowR0 = as.numeric(),
                        upR0 = as.numeric())
  
  
  # For every possible simulation
  for(c in 1:(ncol(df - 1))){
    
    # Get incidence
    incidence <- data.frame(cases = df[,c])
    incidence$cases <- rbinom(n = length(incidence$cases),
                              size = incidence$cases,
                              prob = rho)
    incidence$day <- 2*7 + 1:dim(incidence)[1]
    
    # Make sure there are cases in the first 2 observed weeks...
    somecases <- (sum(incidence$cases[1:14]) >= 12)
    
    if (somecases){
      #== simple EpiEstim: biweekly sliding window
      
      epestim <- epiestim(incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si)
    
      results <- rbind(results, data.frame(
        sim = c, method = 'simpleEpiEstim', R0 = epestim[1],
        lowR0 = epestim[2], upR0 = epestim[3]
      ))
      
      
      #== Linear Exponential Growth: estimate using first 2 weeks 
      if(any(incidence$cases==0)){
        incidence$casesC <- incidence$cases+0.5
        incidence$logcases <- log(incidence$casesC)
      }else{
        incidence$logcases <- log(incidence$cases)
      }
      
      eglin <- EG_Lin(data = incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si)
      
      results <- rbind(results, data.frame(
        sim = c, method = 'EgLin', R0 = eglin[1],
        lowR0 = eglin[2], upR0 = eglin[3]
      ))
      
      
     
      #== EpiEstim with correction
      
      ## Mine as well
      epestim2 <- epiestim_adjust(data = incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si, adjust = TRUE)
      
      epestim2 <- epestim2$results
      results <- rbind(results, data.frame(
          sim = c, method = 'EpiEstim_adjusted', R0 = epestim2[1],
          lowR0 = epestim2[2], upR0 = epestim2[3]
      ))
      
    }
  }
    
    
  rownames(results) <- c()
  
  
  # show results:
  trueR0 <- as.numeric(stringr::str_match(name, "R0=\\s*(.*?)\\s*pop")[2])
  
  results$method <- as.factor(plyr::revalue(results$method, 
                                            c("EgLin"="EG", "EpiEstim_adjusted"="EpEsAdj", "simpleEpiEstim"="EpEs")))
  results <- results %>% group_by(method)
  
  # This is stupid but otherwise I can t get it to work:
  if(trueR0 == 1.5){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 1.5),col = "red", linetype = "dashed")
  }
  if(trueR0 == 2){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 2),col = "red", linetype = "dashed")
  }
  if(trueR0 == 2.5){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 2.5),col = "red", linetype = "dashed")
  }
  if(trueR0 == 3){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 3),col = "red", linetype = "dashed")
  }
  
  # fix style
  gg <- gg + theme_minimal() +  theme(legend.position = 'none') + labs( x = '', y = 'R0 estimate')
  # common xylimits
  gg <- gg + ylim(c(0,4))
  
  list_plots[[name]] <- gg
  # ggsave(plot = gg, filename = file.path(plots_path, paste0("underreporting_.5",name, ".png")))
  
  results$inside <- (trueR0 <= results$upR0 & trueR0 >= results$lowR0)
  results$CIwidth <- results$upR0 - results$lowR0

  tmp <- results %>% group_by(method) %>%
    summarise(coverage = mean(inside), CIwidth = mean(CIwidth),
              q_Rt05 = quantile(R0, .05), q_Rt50 = quantile(R0, .50), q_Rt95 = quantile(R0, .95),
              R0 = trueR0)
  
  final_stats <- rbind(final_stats, tmp)
}

knitr::kable(final_stats)
final_stats$rho <- rho
coverage_stats <- rbind(coverage_stats, final_stats)

figure <- ggarrange(list_plots[[names[1]]], list_plots[[names[2]]], list_plots[[names[3]]], list_plots[[names[4]]],
                    labels = c("R0 = 1.5", "R0 = 2", "R0 = 2.5", "R0 = 3"),
                    ncol = 2, nrow = 2)
figure
ggsave(file.path(plots_path,paste0('figure2_sens',rho,'.png')),figure, w = 10, h = 6.5)
ggsave(file.path(plots_path,paste0('figure2_sens',rho,'.pdf')),figure, w = 10, h = 6.5)
```

### rho = 0.15

Let's a code!
```{r, warning=FALSE, message = FALSE}

# reporting rate
rho <- .15

# Problems showing plots: maybe store them in a list
list_plots <- list()
final_stats <- data.frame(method = as.character(),
                          coverage = as.numeric(),
                          R0 = as.character(),
                          CIwidth = as.numeric())

estimated_starts <- data.frame(R0 = as.character(),
                               estimate = as.numeric())

for (name in names){
  
  # Transform the data
  df <- as.data.frame(sims_SEIR[[name]])
  df$day <- 1:(dim(df)[1])
  
  # Now cut off 2 weeks of data
  df <- filter(df, day > 2*7)
  
  results <- data.frame(sim = as.numeric(),
                        method = as.character(),
                        R0 = as.numeric(),
                        lowR0 = as.numeric(),
                        upR0 = as.numeric())
  
  
  # For every possible simulation
  for(c in 1:(ncol(df - 1))){
    
    # Get incidence
    incidence <- data.frame(cases = df[,c])
    incidence$cases <- rbinom(n = length(incidence$cases),
                              size = incidence$cases,
                              prob = rho)
    incidence$day <- 2*7 + 1:dim(incidence)[1]
    
    # Make sure there are cases in the first 2 observed weeks...
    somecases <- (sum(incidence$cases[1:14]) >= 12)
    
    if (somecases){
      #== simple EpiEstim: biweekly sliding window
      
      epestim <- epiestim(incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si)
    
      results <- rbind(results, data.frame(
        sim = c, method = 'simpleEpiEstim', R0 = epestim[1],
        lowR0 = epestim[2], upR0 = epestim[3]
      ))
      
      
      #== Linear Exponential Growth: estimate using first 2 weeks 
      if(any(incidence$cases==0)){
        incidence$casesC <- incidence$cases+0.5
        incidence$logcases <- log(incidence$casesC)
      }else{
        incidence$logcases <- log(incidence$cases)
      }
      
      eglin <- EG_Lin(data = incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si)
      
      results <- rbind(results, data.frame(
        sim = c, method = 'EgLin', R0 = eglin[1],
        lowR0 = eglin[2], upR0 = eglin[3]
      ))
      
      
     
      #== EpiEstim with correction
      
      ## Mine as well
      epestim2 <- epiestim_adjust(data = incidence[1:14, 1:2], mean_GT = mean_si, sd_GT = sd_si, adjust = TRUE)
      
      epestim2 <- epestim2$results
      results <- rbind(results, data.frame(
          sim = c, method = 'EpiEstim_adjusted', R0 = epestim2[1],
          lowR0 = epestim2[2], upR0 = epestim2[3]
      ))
      
    }
  }
    
    
  rownames(results) <- c()
  
  
  # show results:
  trueR0 <- as.numeric(stringr::str_match(name, "R0=\\s*(.*?)\\s*pop")[2])
  
  results$method <- as.factor(plyr::revalue(results$method, 
                                            c("EgLin"="EG", "EpiEstim_adjusted"="EpEsAdj", "simpleEpiEstim"="EpEs")))
  results <- results %>% group_by(method)
  
  # This is stupid but otherwise I can t get it to work:
  if(trueR0 == 1.5){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 1.5),col = "red", linetype = "dashed")
  }
  if(trueR0 == 2){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 2),col = "red", linetype = "dashed")
  }
  if(trueR0 == 2.5){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 2.5),col = "red", linetype = "dashed")
  }
  if(trueR0 == 3){
    gg <- ggplot(data = results, aes(y = R0, x = method, fill = method)) + geom_violin() +
      geom_hline(aes(yintercept = 3),col = "red", linetype = "dashed")
  }
  
  # fix style
  gg <- gg + theme_minimal() +  theme(legend.position = 'none') + labs( x = '', y = 'R0 estimate')
  # common xylimits
  gg <- gg + ylim(c(0,4))
  
  list_plots[[name]] <- gg
  # ggsave(plot = gg, filename = file.path(plots_path, paste0("underreporting_.5",name, ".png")))
  
  results$inside <- (trueR0 <= results$upR0 & trueR0 >= results$lowR0)
  results$CIwidth <- results$upR0 - results$lowR0

  tmp <- results %>% group_by(method) %>%
    summarise(coverage = mean(inside), CIwidth = mean(CIwidth),
              q_Rt05 = quantile(R0, .05), q_Rt50 = quantile(R0, .50), q_Rt95 = quantile(R0, .95),
              R0 = trueR0)
  
  final_stats <- rbind(final_stats, tmp)
  
}

knitr::kable(final_stats)
final_stats$rho <- rho
coverage_stats <- rbind(coverage_stats, final_stats)# extract legend
g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

figure <- ggarrange(list_plots[[names[1]]], list_plots[[names[2]]], list_plots[[names[3]]], list_plots[[names[4]]],
                    labels = c("R0 = 1.5", "R0 = 2", "R0 = 2.5", "R0 = 3"),
                    ncol = 2, nrow = 2)
figure
ggsave(file.path(plots_path,paste0('figure2_sens',rho,'.png')),figure, w = 10, h = 6.5)
ggsave(file.path(plots_path,paste0('figure2_sens',rho,'.pdf')),figure, w = 10, h = 6.5)
```

### Coverage and CI width plot


```{r}
coverage_stats$method <- as.factor(plyr::revalue(coverage_stats$method, c("EgLin"="EG", "EpiEstim_adjusted"="EpEsAdj", "simpleEpiEstim"="EpEs")))
coverage_stats$R0 <- as.factor(coverage_stats$R0)
coverage_stats$R0 <- as.factor(plyr::revalue(coverage_stats$R0, c("1.5"="R0 = 1.5", "2"="R0 = 2", "2.5"="R0 = 2.5", "3"="R0 = 3")))

coverage_stats$rho <- as.factor(coverage_stats$rho)

rm <- theme_bw() + theme(axis.title.x=element_blank()) +  theme(legend.position = 'none') 

oo <- ggplot(coverage_stats, aes(x = method, col = rho, fill = rho)) +
  geom_errorbar(aes(ymin = q_Rt05, ymax = q_Rt95), position = position_dodge(.6), width = .5, alpha=.5) +
  geom_point(aes(y = q_Rt50), position = position_dodge(.6)) + 
  geom_hline(aes(yintercept = as.numeric(gsub("R = ", "", R0))), linetype = 'dashed')+
  facet_grid(cols = vars(R0)) + ylab('median')
  labs(fill = "Reporting \nrate", col = 'Reporting \nrate') 

pp <- ggplot(coverage_stats, aes(x = method, y = coverage, col = rho, fill = rho)) +
  geom_hline(aes(yintercept = .95), linetype = 'dashed')+
  geom_bar(stat="identity",position = "dodge", alpha=.3) + facet_grid(cols = vars(R0)) +
  labs(fill = "Reporting \nrate", col = 'Reporting \nrate') 

qq <- ggplot(coverage_stats, aes(x = method, y = CIwidth, col = rho, fill = rho)) + 
  geom_bar(stat="identity",position = "dodge", alpha=.3) + facet_grid(cols = vars(R0)) +
  labs(y = 'CI/CrI width')

mylegend<-g_legend(pp)

tmp <- ggarrange(oo + rm, pp + rm, qq + rm,
                 labels="AUTO",
                 ncol = 1) 

gg <- ggarrange(tmp, mylegend,
          widths = c(10,1),
          ncol = 2) 

ggsave(file.path(plots_path,'figure3.png'), gg, w = 10, h = 7)
ggsave(file.path(plots_path,'figure3.pdf'), gg, w = 10, h = 7)

```

